# Set up verbose commands
/control/verbose 0
/run/verbose 0
/run/initialize
/tracking/verbose 0
/event/verbose 0

#/gps/particle gamma
#/gps/ene/type Mono
#/gps/ene/mono 6. keV
#/gps/pos/centre 0 0 80 mm
#/gps/ang/type iso
#/gps/ang/mintheta 179 deg

/gun/particle gamma
/gun/energy 6. keV
/gun/direction 0 0 -1
/gun/position 0 0 80 mm


/analysis/setFileName test_fe55.root
/run/setCut 0.5 um
/run/beamOn 100000


